### ISSUE TITLE
🔥

### ISSUE THREAD

**Issue by H3XDaemon** [GeekTR/PrivacySpace#1]
啟用重啟後手機直接燒起來 >1500mA/h
LSPosed log噴到 - - - -part 3315 start- - - -
系統OxygenOS Android 11

**Comment by GeekTR** [comment]
对你造成麻烦表示抱歉，可以麻烦提供一下LSPosed的log吗？

**Comment by GeekTR** [comment]
1.2版本兼容性比较好，就是需要root权限

**Comment by H3XDaemon** [comment]
> 对你造成麻烦表示抱歉，可以麻烦提供一下LSPosed的log吗？
[logs.zip](https://github.com/GeekTR/PrivacySpace/files/8161835/logs.zip)

**Comment by GeekTR** [comment]
> 
感谢，这个bug将在下个版本被修复。

**Comment by GeekTR** [comment]
已修复
