### ISSUE TITLE
大哥你好

### ISSUE THREAD

**Issue by qloop1** [GeekTR/PrivacySpace#12]
大哥你好，本人设置了白名单内只有一个微信，大部分app都没问题，但是有个app还是能检测到我装了gg修改器，只有随他致盲，才能彻底隐藏
![Screenshot_20220731-201605](https://user-images.githubusercontent.com/91721008/182025986-9e069387-4447-4329-ab89-de0e9eb091aa.jpg)

**Comment by GeekTR** [comment]
对不起，我不想回答外挂相关的问题
