### ISSUE TITLE
请问致盲是什么意思？

### ISSUE THREAD

**Issue by Frank997** [GeekTR/PrivacySpace#13]
请问菜单中的“致盲”是做什么的？

**Comment by httpsColon** [comment]
隐秘空间软件说明书：
软件作用：可以全局隐藏app的软件
使用前提：
1. xposed软件
2. 勾选作用域（一般推荐作用域即可,不需要专门勾选部分应用）
主要功能介绍
1. 致盲：选中的应用后,默认让应用无法读取到系统应用清单（目前效果是读取到的应用清单为大部分系统应用,其无法读到少部分系统应用以及所有三方应用）

2. 隐藏app：仅仅需要把app添加模块中即可,默认全局隐藏,默认隐藏本身（即隐秘空间app）,还可以隐藏双开应用（隐藏时默认隐藏应用本体和其分身，如果只想隐藏分身可以长按图标选择不需要隐藏的用户就可以）
通俗的说假如你把微信加入了,而你微信已经多开了,默认会把微信及其分身添加,如果只想隐藏本体或分身,则长按--多用户配置--勾选想要隐藏的取消勾线不想隐藏的

3.白名单：白名单内的app可以正常获取到已隐藏的app（单向）

4.关联：关联后的两个app互相可见（双向）

5. 让隐藏的应用显示在桌面：长按隐藏app图标,出现菜单,点击关联桌面后,点击右上角三角菜单--重启桌面即可看到想要显示隐藏的应用

注意：所有致盲、隐藏功能为即时生效

**Comment by Frank997** [comment]
> 隐秘空间软件说明书： 软件作用：可以全局隐藏app的软件 使用前提：
> 
>     1. xposed软件
> 
>     2. 勾选作用域（一般推荐作用域即可,不需要专门勾选部分应用）
>        主要功能介绍
> 
>     3. 致盲：选中的应用后,默认让应用无法读取到系统应用清单（目前效果是读取到的应用清单为大部分系统应用,其无法读到少部分系统应用以及所有三方应用）
> 
>     4. 隐藏app：仅仅需要把app添加模块中即可,默认全局隐藏,默认隐藏本身（即隐秘空间app）,还可以隐藏双开应用（隐藏时默认隐藏应用本体和其分身，如果只想隐藏分身可以长按图标选择不需要隐藏的用户就可以）
>        通俗的说假如你把微信加入了,而你微信已经多开了,默认会把微信及其分身添加,如果只想隐藏本体或分身,则长按--多用户配置--勾选想要隐藏的取消勾线不想隐藏的
> 
> 
> 3.白名单：白名单内的app可以正常获取到已隐藏的app（单向）
> 
> 4.关联：关联后的两个app互相可见（双向）
> 
>     5. 让隐藏的应用显示在桌面：长按隐藏app图标,出现菜单,点击关联桌面后,点击右上角三角菜单--重启桌面即可看到想要显示隐藏的应用
> 
> 
> 注意：所有致盲、隐藏功能为即时生效

 谢谢
