### ISSUE TITLE
求支持miui14

### ISSUE THREAD

**Issue by FairyWorld** [GeekTR/PrivacySpace#16]

**Comment by GeekTR** [comment]
电报群里面有兼容Android13的测试版，正式版晚一些再发布。https://t.me/PrivacySpaceAlpha

**Comment by AinzOoal13** [comment]
> 电报群里面有兼容Android13的测试版，正式版晚一些再发布。https://t.me/PrivacySpaceAlpha

Where is the link i am in the group wich link is it?

**Comment by GeekTR** [comment]
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/13369103/211147367-52e526bf-add3-479d-b144-3a4d51015e1d.png">
