### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by AinzOoal13** [GeekTR/PrivacySpace#18]
Hello i love This Modul i use it on my S8 its a android 9 phone, but i wanna used it on my Android 13 to. I have a question if you will make a update for this modul for android 12 or 13?

**Comment by GeekTR** [comment]
The Telegraph group has a beta version compatible with Android 13, the official version will be released later

**Comment by GeekTR** [comment]
https://t.me/PrivacySpaceAlpha

**Comment by AinzOoal13** [comment]
> The Telegraph group has a beta version compatible with Android 13, the official version will be released later

I found it thank you again, i dont know how but this modul is amazing i can install a application again from Playstore or internet.

Thanks again how long you spend in this project?
