### ISSUE TITLE
Click the `Restart Settings App` button but the toast says `Security restart successfully`

### ISSUE THREAD

**Issue by deltazefiro** [GeekTR/PrivacySpace#19]
Hi. Thank you for developing such a nice app!  
But I believe I found a tiny bug: When I click the button `Restart Settings App`, a toast pops out and says `Security restart successfully`.  

https://github.com/GeekTR/PrivacySpace/blob/728c6f41bafc6d2a036f9a8a5e565ac1d3b5003c/app/src/main/java/cn/geektang/privacyspace/ui/screen/launcher/LauncherScreen.kt#L505-L511

**Comment by GeekTR** [comment]
Thanks for your feedback, I will fix it in the next version
