### ISSUE TITLE
Android version 14 not supported??

### ISSUE THREAD

**Issue by HGNEO** [GeekTR/PrivacySpace#22]
I tried this module on my crdroid v10 bases on android 14 on my mi pad 5 but ijt is  showing module not activatd sir please fix this sir I really am love with this thing

**Comment by GeekTR** [comment]
try the newly uploaded new version of the app.

**Comment by GeekTR** [comment]
[https://github.com/Xposed-Modules-Repo/cn.geektang.privacyspace/releases/tag/10311-1.3.11](https://github.com/Xposed-Modules-Repo/cn.geektang.privacyspace/releases/tag/10311-1.3.11)
